install:
	  mkdir -p ~/.hello-world-py-cli &&\
	  python3 -m venv ~/.hello-world-py-cli &&\
	  pip install -r requirements.txt


source-cmd:
	echo "Virtualenv source command"
	#source ~/.hello-world-py-cli/bin/activate

lint:
	pylint hello-world.py